### ISSUE TITLE
Extend adapter to read Displacements (and allow configuration)

### ISSUE THREAD

**Issue by MakisH** [precice/su2-adapter#17]
The adapter currently only reads DisplacementDeltas and writes Forces:

https://github.com/precice/su2-adapter/blob/f3a8ef1f48d1b5a6c06b4903c6610bfb713ac87e/adapter_files/precice.cpp#L249-L251

We also need to be able to read Displacements, as not every structure solver we have supports DisplacementDeltas.

Moreover, the data names are currently hard-coded. We should add two options in the configuration file to configure what the adapter writes and reads:

https://github.com/precice/su2-adapter/blob/f3a8ef1f48d1b5a6c06b4903c6610bfb713ac87e/replacement_files/config_structure.cpp#L2013-L2034

**Comment by DavidSCN** [comment]
Is anyone working on this task? It's a prerequisite for https://github.com/precice/tutorials/issues/135.

**Comment by IshaanDesai** [comment]
> Is anyone working on this task?

AFAIK nobody is currently working on this.

**Comment by Ccaccia73** [comment]
I first started porting SU2 to current version (7.0.8) but still sort of WIP

**Comment by MakisH** [comment]
The adapter now uses the Python wrapper of SU2 and couples displacement by default.
Besides, the previous adapter supported displacements since #21.
