### ISSUE TITLE
Extend adapter to handle Quasi 2D-3D coupling

### ISSUE THREAD

**Issue by IshaanDesai** [precice/su2-adapter#18]
When SU2 is coupled in a quasi 2D-3D manner to other solvers, the dimensions specified by preCICE is 3 but the mesh provided to SU2 is 2. Currently there is an assertion in the adapter to prevent such a configuration from running.
For example with the perpendicular flap tutorial case for SU2-CalculiX, the only reason why SU2 uses a 3D mesh (with one dimension having a single) is that CalculiX is 3D. It would be easier for a SU2 user to just specify a 2D mesh and the adapter handle quasi 2D-3D coupling.

**Open question**: Which direction does the adapter ignore when a quasi 2D-3D coupling is defined? Usually the X-dimension is always valid and either of Y- or Z- are ignored. For example, in the `fenics-adapter` the Z-direction is ignored. But for the SU2-CalculiX perpendicular flap case the Y-direction is ignored. A decision will help in implementation.

**Comment by Ccaccia73** [comment]
Hi, I don't know if this answers your question but, afaik, it is possible to give a 2D mesh to the SU2 adapter. It must be in the x-y plane, otherwise SU2 won't start, even if the error message isn't very clear.  If you have to keep the solution 3D I think you should be able to define the plane yourself and the use something like z-dead=true in the mapping.

**Comment by IshaanDesai** [comment]
Hi @Ccaccia73 , I think it is not possible to define a 3D coupling problem and provide a 2D mesh to SU2 because the adapter has an assertion:
https://github.com/precice/su2-adapter/blob/9761fd8e22d785592e912ccb6aad5d22e0dcaf29/adapter_files/precice.cpp#L169-L173
This assertion prevents a 2D-3D coupling to be run with SU2. The adapter should be able to handle a case when preCICE provides `dimension=3` and the user provides a 2D mesh.

**Comment by Ccaccia73** [comment]
Yes, you are totally right. I was thinking you needed a 2D coupling in preCICE. I meant that you can define a 2D mesh in SU2 in the x-y plane, and connect it with preCICE. If on the other side you have an intrinsecally 3D solver, you need to enforce 2D behaviour in it and couple with dimension=2, if possible.

**Comment by IshaanDesai** [comment]
Indeed @Ccaccia73! An alternative strategy is suggested to handle this: https://github.com/precice/tutorials/issues/112#issuecomment-719442408 
For a 2D-3D coupling the dimensions in preCICE will be defined as `dimensions=2`. The 3D solver on the other side will ignore data in one direction before writing data to preCICE. This allows SU2 to work with a 2D case.
