### ISSUE TITLE
m2n communication with files

### ISSUE THREAD

**Issue by davide5grana** [precice/su2-adapter#2]
Hi, 

i'm trying to run the testcase changing m2n from _socket_ to _files_, but i've got those errors on launching the two solvers:

Calculix:
ASSERTION FAILED
  Location:          src/com/FileCommunication.cpp:262
  Rank:              0
  Failed expression: _sendFile.is_open()

SU2
ASSERTION FAILED
  Location:          src/com/FileCommunication.cpp:379
  Rank:              0
  Failed expression: _receiveFile.is_open()

i've changed the config file in this way:
 <m2n:files from="SU2_CFD" to="Calculix"  exchange-directory="."/>

What's was wrong?

Thanks

**Comment by floli** [comment]
When you start SU2 and Calculix, is your current working directory the same for both?

Also, did you try another m2n communication scheme, such as sockets?

**Comment by davide5grana** [comment]
yes, the directory is the same. 
I've tried with socket communication and its' fine.

**Comment by floli** [comment]
Can't help with this issue then, but I would just stick to socket communication. File based is rather for debugging and performs badly.

**Comment by uekerman** [comment]
File Communication is deprecated in m2n. You should get an error message. I
will have a look why this is not the case. Please let us know if your
application or setup relies for any reason on file communication.
Benjamin

On Oct 3, 2017 10:31 AM, "Florian Lindner" <notifications@github.com> wrote:

Can't help with this issue then, but I would just stick to socket
communication. File based is rather for debugging and performs badly.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/precice/su2-adapter/issues/2#issuecomment-333775718>,
or mute the thread

**Comment by davide5grana** [comment]
I need files communication in order to match a different CFD solver, that should replace SU2...at least for this starting debugging stage. Thank you

**Comment by uekerman** [comment]
I don't fully understand your plan yet, but I think there is a better way to get where you want. For debugging, you could let preCICE write vtk output. Simply add this line to the participant in your config:
`<export:vtk timestep-interval="1" directory="." every-iteration="no" />`. Do you run both solvers in serial? If so, file communication should still work. You need a `distribution-type="gather-scatter"` though. 
If you want, you can explain in more detail what your plan is and we can tell you what the best approach from preCICE perspective would be. Which CFD solver do you want to couple? Can you attach your current config file? Thanks

**Comment by davide5grana** [comment]
Thanks for replay.

Now I just want to reproduce the standard calculix-su2 test case, changing m2n to "files"...so the config file is the same except in m2n section. 


 changed line:
>  <m2n:files from="SU2_CFD" to="Calculix"  exchange-directory="../" distribution-type="gather-scatter"/>

**Comment by davide5grana** [comment]
To give additional info i attach the message error: 

ASSERTION FAILED
  Location:          src/com/FileCommunication.cpp:262
  Rank:              0
  Failed expression: _sendFile.is_open()
Stack Trace:
  (12)  /preCICE/precice/build/last/libprecice.so : precice::com::FileCommunication::send(int, int)+0x112
  (11)  /preCICE/precice/build/last/libprecice.so : precice::com::CommunicateMesh::sendMesh(precice::mesh::Mesh const&, int)+0x6f2
  (10)  /preCICE/precice/build/last/libprecice.so : precice::geometry::CommunicatedGeometry::sendMesh(precice::mesh::Mesh&)+0x1e7e
  ( 9)  /preCICE/precice/build/last/libprecice.so : precice::geometry::CommunicatedGeometry::prepare(precice::mesh::Mesh&)+0xad9
  ( 8)  /preCICE/precice/build/last/libprecice.so : precice::impl::SolverInterfaceImpl::prepareGeometry(precice::impl::MeshContext&)+0x15e7
  ( 7)  /preCICE/precice/build/last/libprecice.so : precice::impl::SolverInterfaceImpl::initialize()+0x1e73
  ( 6)  /preCICE/precice/build/last/libprecice.so : precicec_initialize()+0x17b
  ( 5)  /preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE : ) [0x5be42b]()+/u1/cida661/preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE(
  ( 4)  /preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE : ) [0x5a5bef]()+/preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE(
  ( 3)  /preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE : ) [0x40a510]()+/preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE(
  ( 2)  /lib64/libc.so.6 : __libc_start_main()+0xf5
  ( 1)  /preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE : ) [0x4163af]()+/preCICE/adpCalculix/calculix-adapter-master/bin/ccx_preCICE(ccx_preCICE: src/com/FileCommunication.cpp:262: virtual void precice::com::FileCommunication::send(int, int): Assertion `false' failed.

**Comment by uekerman** [comment]
This is indeed a bug. I could reproduce your problem. We appreciate the feedback! 
Unfortunately, however, we will probably not fixed this problem, but disable file communication completely in the upcoming release (coming soon). I would like to find out better why you use file communication. From our perspective there is no reason any longer why this feature is needed, but maybe we are wrong. I am confident that we can help you in a better way. Feel free to write to the preCICE mailing list. We could also arrange a hangout call.

**Comment by davide5grana** [comment]
Dear,

thanks for your feedback.

I need to understand what and in which way the precice lib exchange information with SU2, since I want to replace SU2 in the FSI chain with our CFD solvers.
This could be not so efficient, but in the early stage can be helpful to set up the calculations.

Partially, those info are contained in the vtk file that preCICE writes down?

Thank you

Davide Cinquegrana


Da: Benjamin Uekermann [mailto:notifications@github.com]
Inviato: lunedì 9 ottobre 2017 11:20
A: precice/su2-adapter <su2-adapter@noreply.github.com>
Cc: Cinquegrana Davide <D.Cinquegrana@cira.it>; Author <author@noreply.github.com>
Oggetto: Re: [precice/su2-adapter] m2n communication with files (#2)


This is indeed a bug. I could reproduce your problem. We appreciate the feedback!
Unfortunately, however, we will probably not fixed this problem, but disable file communication completely in the upcoming release (coming soon). I would like to find out better why you use file communication. From our perspective there is no reason any longer why this feature is needed, but maybe we are wrong. I am confident that we can help you in a better way. Feel free to write to the preCICE mailing list. We could also arrange a hangout call.

**Comment by floli** [comment]
Dear Davide,
we are happy to support you in using preCICE, but this issue has veered off-topic. I would suggest we continue hat the preCICE mailing list, which is the right place for more general discussions:

https://mailman.informatik.uni-stuttgart.de/mailman/listinfo/precice

Best!
