### ISSUE TITLE
Reading absolute displacement data doesn't support extrapolation

### ISSUE THREAD

**Issue by davidscn** [precice/su2-adapter#22]
The SU2 adapter was initially designed for displacement deltas. We extended the read data capability for absolute read data in https://github.com/precice/su2-adapter/pull/21 using the following logic:
```cpp
        case ReadDataType::Displacement: {
          for (int iVertex = 0; iVertex < vertexSize[i]; iVertex++) {
            for (int iDim = 0; iDim < nDim; iDim++) {
              displacementDeltas_su2[iVertex][iDim] =
                  displacements[iVertex * nDim + iDim] - displacements_n[iVertex * nDim + iDim];

              if (solverInterface.isTimeWindowComplete()) {
                displacements_n[iVertex * nDim + iDim] = displacements[iVertex * nDim + iDim];
              }
            }
          }
          break;
        }
```
i.e. we compute the delta from the absolute displacement of the previous time window. The motivation was given due to the tutorial restructuring precice/tutorials#125. However, this approach does not allow to use an extrapolation in the precice configuration, see https://github.com/precice/su2-adapter/pull/21#issuecomment-767627857, since we would store extrapolated data.

**Comment by DavidSCN** [comment]
We should at least add an Assertion here before the release, otherwise one will obtain erroneous results without knowing it. Since we cannot ask preCICE for configuration parameter, I don't have any idea how to assert this at the moment.

**Comment by MakisH** [comment]
@DavidSCN what is the plan regarding this issue now?

**Comment by DavidSCN** [comment]
Discuss in a few minutes with somebody an appropriate solution.

**Comment by MakisH** [comment]
We decide that we keep this open, but document this for now in the adapter documentation. This is a real issue that we should address by reimplementing absolute displacement (or killing extrapolation in preCICE, in the very long future).

**Comment by DavidSCN** [comment]
I added a warning in the website documentation of the SU2-adapter.

**Comment by MakisH** [comment]
This should not be relevant with the rewritten adapter, which uses the Python wrapper of SU2.
Please reopen if needed.

**Comment by uekerman** [comment]
We also removed extrapolation in preCICE with v3.
