### ISSUE TITLE
su2-adapter installation failed

### ISSUE THREAD

**Issue by MatthiasFreimuth** [precice/su2-adapter#4]
I'm trying to compile SU2 with the precice-su2-adapter as described on this github-page. Especially i try to build the AD-version of SU2(see https://su2code.github.io/docs/AD-Build/). Running the SU2 make install command i get the following error corresponding to parts of the replaced files:

In (...) driver_structure.cpp:2981:68: error: cannot convert ‘su2double {aka codi::ActiveReal<codi::JacobiTape<codi::ChunkTapeTypes<double, codi::LinearIndexHandler<int> > > >}’ to ‘double’ in initialization
dt = new double(config_container[ZONE_0]->GetDelta_UnstTimeND());
^
Makefile:2748: recipe for target '../src/___bin_SU2_CFD_AD-driver_structure.o' failed

The corresponding lines in the driver_structure.cpp file are:

```//preCICE
  precice_usage = config_container[ZONE_0]->GetpreCICE_Usage();
  if (precice_usage) {
    precice = new Precice(rank, size, geometry_container, solver_container, config_container, grid_movement);
    dt = new double(config_container[ZONE_0]->GetDelta_UnstTimeND());
    precice->configure(config_container[ZONE_0]->GetpreCICE_ConfigFileName());
    max_precice_dt = new double(precice->initialize());
  }
```

I use SU2 version 6.0.0 and preCICE version 1.2.0 on Ubuntu 18.04.1 LTS. The preCICE tests work fine if I ignore the mpi and petsc rbf tests as suggested.

**Comment by fsimonis** [comment]
It seems that [su2double](https://github.com/su2code/SU2/blob/5d5571f7fc9e4b0f77d093b31d593e5fc94f426f/Common/include/datatypes/codi_reverse_structure.hpp) is a codi type. To access its value one has to call [value()](https://www.scicomp.uni-kl.de/codi/d1/dff/classcodi_1_1ActiveReal.html#a9548ee558bb139ca455fa1f8818e208d) or 
[getValue()](https://www.scicomp.uni-kl.de/codi/dd/de5/structcodi_1_1Expression.html#a8cad088e28228110bf48f9ac3768a1c7).

Please try to change
```cpp
dt = new double(config_container[ZONE_0]->GetDelta_UnstTimeND());
```
to
```cpp
dt = new double(config_container[ZONE_0]->GetDelta_UnstTimeND().value());
// or
dt = new double(config_container[ZONE_0]->GetDelta_UnstTimeND().getValue());
```

**Comment by talbring** [comment]
If you configure SU2 using the preconfigure.py script, the usual 'configure' command is called twice (in different folders). Once with su2double = double and once with su2double = codi::ActiveReal. So in both cases the code is the same, but the underlying datatype is different. In order to get the underlying double value, always use SU2_TYPE::GetValue(...). This routine is implemented for both types. So I would suggest to replace all occurrences of double in you replaced files with su2double. Then extract the double values  before passing it to the precice interface.

**Comment by MakisH** [comment]
Thanks a lot, @talbring! @MatthiasFreimuth can you try if this is enough in your case, or if we have more problems? If yes, I will fix the replacement files today.

**Comment by MatthiasFreimuth** [comment]
I'm working on it. But there appear a lot of changes in the precice.cpp file I'm dealing with right now.

**Comment by MatthiasFreimuth** [comment]
I changed several things in driver_structure.cpp, precice.cpp and precice.hpp now and the installation was successfull in a way that there no longer occur errors. The FSI tutorial with preCICE and SU2 works fine, so at least the not-AD-concerning functions of SU2 seem to work. I will try to figure out next, whether the discrete adjoint solvers(benefit of the AD-build) will work in a preCICE-coupled simulation.

**Comment by MakisH** [comment]
Thanks, @MatthiasFreimuth ! Can you maybe document here what you changed, or give some hints of what else you changed? Exporting a diff patch (e.g. with Meld) would be very nice. Opening a pull request would be awesome!

**Comment by MatthiasFreimuth** [comment]
As I'm not that familiar with git, I preferred to make the diff patches with Meld:

[Differences.zip](https://github.com/precice/su2-adapter/files/2519592/Differences.zip)

**Comment by MakisH** [comment]
This should not be relevant with the rewritten adapter, which uses the Python wrapper of SU2.
Please reopen if needed.
