### ISSUE TITLE
incompressible regime simulations

### ISSUE THREAD

**Issue by Ccaccia73** [precice/su2-adapter#8]
Hi,
I'm trying to couple SU2 to a structural solver via PreCICE. In my case the fluid part considers an incompressible fluid in laminar regime. My simulations stop at the first fluid iteration with:

_preCICE:ERROR:  The computed timestep length of 0.000513 exceeds the maximum timestep limit of 0.000487 for this time step!_

Other simulations, like the "flap-perp" tutorial, work without problems.
I would like to know if PreCICE is able to work with incompressible simulations or it is tailored to compressible ones.
The PreCICE version I'm using is 1.5.2 and SU2 6.0.0

Thank you
Claudio

**Comment by uekerman** [comment]
Hi Claudio,

You error message means that the adapter does not properly call
```c++
dt = min(precice_dt, dt)
```
See also [the wiki page on timestep sizes](https://github.com/precice/precice/wiki/Adapter's-Time-Step-Sizes).

preCICE itself does not "care" about the coupling physics. preCICE merely exchanges data and performs numerical coupling algorithms. The question is whether the SU2 adapter also supports the incompressible SU2 solver. Here, I am not sure. Probably, this has not been tested.

Another option for an incompressible fluid solver would be OpenFOAM. There are also [tutorials using incompressible solvers in OpenFOAM for FSI](https://github.com/precice/precice/wiki#fluid-structure-interaction). 

Please note that we are using issues on GitHub mainly to track code changes (bugs, features, ...), not support. For support, [Discourse](https://precice.discourse.group/) is the best place.
